# Generated by Django 4.2.1 on 2023-05-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_numbers', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('mobile_number', 'contact_numbers')},
            },
        ),
    ]
