# Generated by Django 4.2.1 on 2023-06-06 05:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_numbers', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('active', models.BooleanField(default=True)),
                ('is_spam', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpamCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('spam', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserbasedSpamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
