# Generated by Django 4.2.1 on 2023-06-01 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mobile_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mob_number', to=settings.AUTH_USER_MODEL),
        ),
    ]
