# Generated by Django 4.2.1 on 2023-06-06 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasedspamlist',
            name='mobile_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobnumber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacts',
            name='mobile_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together={('mobile_number', 'contact_numbers')},
        ),
    ]
