# Generated by Django 4.2.1 on 2023-06-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_mobile_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
