# Generated by Django 4.2.1 on 2023-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamcounter',
            name='spam',
            field=models.IntegerField(default=0),
        ),
    ]
