# Generated by Django 4.2.1 on 2023-06-01 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_alter_contacts_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mobile_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together={('mobile_number', 'contact_numbers')},
        ),
    ]
