# Generated by Django 4.2.1 on 2023-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_num', models.IntegerField()),
                ('spam', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
