# Generated by Django 4.2.1 on 2023-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_spamcounter_contacts_is_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamcounter',
            name='spam',
            field=models.IntegerField(default=0),
        ),
    ]
