# Generated by Django 4.2.1 on 2023-06-02 05:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_spamcounter_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_numbers',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='spamcounter',
            name='contact_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
